### ISSUE TITLE
Invalid json syntax in release.json

### ISSUE THREAD

**Issue by QartemisT** [tflo/PetWalker#1]
For the release of 1.0.4, the "release.json" file you provide is in invalid syntax, it is missing a `}` at the end.

**Comment by tflo** [comment]
Fixed. Thanks for the note.

**Comment by QartemisT** [comment]
Hi there, noticed a few extra issues, such as metadata missing etc. So decided to just provide you with a completely fixed JSON markup;

`{"releases":[{"filename":"PetWalker-1.0.4.zip","nolib":false,"metadata":[{"flavor":"mainline","interface":90205}]}]}`
