### ISSUE TITLE
Can't set new pet for autosummoning

### ISSUE THREAD

**Issue by Akicita33** [tflo/PetWalker#14]
I had Ethereal Soul-Trader set as my pet to auto-summon, but I no longer want that pet to be summoned. Every time I try to summon a new pet it keeps replacing it with EST. What do I do to fix this?

**Comment by tflo** [comment]
If you try to summon the new pet by any means other than right-clicking in the Pet Journal (e.g., from an actionbar button), please update to version [2.3.0](https://www.curseforge.com/wow/addons/petwalker/files/5785023). PW before 2.3.0 did not save pets summoned from actionbar buttons, replacing them with the previously saved pet.

Related: Issues #12 and #13

If this is not the case, or you are already using PW 2.3.0, then I need more info. (Depending on your setup, you could for example try to remove the EST from your favorites, or disable the auto-summon timer.)

**Comment by Akicita33** [comment]
Dude, I owe you an apology, it was my fault. i had coded the EST into my mounting macro, that is what was summoning that pet. You're addon is doing exactly what it's supposed. Sorry for the confusion.

**Comment by tflo** [comment]
No problem.

> You're addon is doing exactly what it's supposed. 

Glad to hear that :)
