### ISSUE TITLE
Asset ZIP is invalid

### ISSUE THREAD

**Issue by QartemisT** [tflo/PetWalker#2]
The asset ZIP you attached to v1.0.4 is invalid;

You have TWO nested folders;
Current: `PetWalker-1.0.4.zip\PetWalker-1.0.4\PetWalker\PetWalker.toc`
Expected: `PetWalker-1.0.4.zip\PetWalker\PetWalker.toc`

I hope this helps :)

**Comment by tflo** [comment]
Thanks for the hint! Just uploaded a new archive with just "PetWalker" as root folder. (Like the one on Wago.)

(The nested folders were an attempt to make it compliant with WoWUp Hub.)
