### ISSUE TITLE
Please share your working Paragon version

### ISSUE THREAD

**Issue by vince2paname** [tflo/PetWalker#4]
Hello Tflo,
I don't know how to reach you, so I try here, maybe I will be luckier :).
I saw your comment here : https://github.com/glassleo/Paragon/issues/4

Is it possible to share the temporary working version you have made ? I'm desperate to find a solution to make this addon work again :)

Thank you, and sorry to post a wrong issue in the wrong section, It seems that it's not possible to send a message to a user within Github, and I don't know any other way to contact you.

**Comment by tflo** [comment]
No need to post here, I got a mail notification of your post in the Paragon issue ;) Give me 2 minutes …
