### ISSUE TITLE
Issue doing quest [Eye See You]

### ISSUE THREAD

**Issue by gizzmo** [tflo/PetWalker#8]
During the quest [[Eye See You]](https://www.wowhead.com/quest=42375/eye-see-you), you have to take control of an Eye of Kilrogg, but the moment you step forward, Pet Walker tries to restore your pet, in turn canceling the Eye. I was able to do the quest with disabling the auto summon (`/pw a`).

It gives you the buff [Eye of kilrogg](https://www.wowhead.com/spell=212754/eye-of-kilrogg). It's a non expiring buff, giving you time to explore the area. Maybe you can check if that buff exists, before you try to summon a pet?

There's only one prerequisite goto quest, shouldn't be too hard to get an alt down there to test it yourself.

**Comment by tflo** [comment]
I tried the quest and added the aura to the exclusions. Thank you very much for reporting!

(This reminded me to add also a vehicle aura from a toy that has exactly the same controls/mechanics (Gastropod Shell).)

It will be included with the next release (after 10.2 launch).

---

These are the currently excluded auras from quests/events/toys/pets:

```lua
	311796, -- Pet: Daisy as backpack (/beckon)
	312993, -- Carrying Forbidden Tomes (Scrivener Lenua event, Revendreth)
	43880, -- Ramstein's Swift Work Ram (Brewfest daily; important bc the quest cannot be restarted if messed up)
	43883, -- Rental Racing Ram (Brewfest daily)
	290460, -- Battlebot Champion (Forbidden Reach: Zskera Vault)
	212754, -- Eye of Kilrogg aura in the context of the Eye See You quest (Azsuna)
	142372, -- Jerry the Snail (Gastropod Shell toy)
```
 

If you come across another one, don't hesitate to let me know!

Thanks again,

– Tom
